//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Cars
{
	public virtual int RedLightTime
	{
		get;
		set;
	}

	public virtual DateTime EndTime
	{
		get;
		set;
	}

	public virtual int CarNumber
	{
		get;
		set;
	}

	public virtual string Direction
	{
		get;
		set;
	}

	public virtual int RedStopCounter
	{
		get;
		set;
	}

	public virtual int X
	{
		get;
		set;
	}

	public virtual int Y
	{
		get;
		set;
	}

	public virtual int CrossingID
	{
		get;
		set;
	}

	public virtual void DrawCar()
	{
		throw new System.NotImplementedException();
	}

	public virtual void MoveToThePoint()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CalculateRedlightTime()
	{
		throw new System.NotImplementedException();
	}

}

