//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Crossing 
{
	public virtual int CrossingID
	{
		get;
		set;
	}

	public virtual List <Feeder> FeederList
	{
		get;
		set;
	}

	public virtual Neighbours Neighbours
	{
		get;
		set;
	}

	public virtual int GridCellNumber
	{
		get;
		set;
	}

	public virtual List<Timers> TimerList
	{
		get;
		set;
	}

	public virtual IEnumerable<Feeder> Feeder
	{
		get;
		set;
	}

	public virtual void AddDetailes()
	{
		throw new System.NotImplementedException();
	}

}

