//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Crossing 
{
    public int CrossingID { get; set; }
    public List<Feeder> Feeders { get; set; }
    public Neighbours neighbors { get; set; }

    public Crossing(int crossingID)
    {
        this.CrossingID = crossingID;
        Feeders = new List<Feeder>();
        neighbors = new Neighbours();

        for (int i = 1; i < 5; i++)
        {
            Feeders.Add(new Feeder(i,this));
        }
    }

	public virtual int GridCellNumber
	{
		get;
		set;
	}

	public virtual List<Timers> TimerList
	{
		get;
		set;
	}

	public virtual IEnumerable<Feeder> Feeder
	{
		get;
		set;
	}

    public virtual void AddDetailes(int feederID, Crossing crossing, int rPercentage, int lPercentage, int sPercentage, int carQuantity, int pedTimer)
	{
		
	}

}

