//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Crossing 
{
    public int CrossingID { get; set; }
    public List<Feeder> Feeders { get; set; }
    public Neighbours neighbors { get; set; }

    public Crossing(int crossingID)
    {
        this.CrossingID = crossingID;
        Feeders = new List<Feeder>();
        neighbors = new Neighbours();
    }

	public virtual List <Feeder> FeederList
	{
		get;
		set;
	}

	public virtual Neighbours Neighbours
	{
		get;
		set;
	}

	public virtual int GridCellNumber
	{
		get;
		set;
	}

	public virtual List<Timers> TimerList
	{
		get;
		set;
	}

	public virtual IEnumerable<Feeder> Feeder
	{
		get;
		set;
	}

	public virtual void AddDetailes()
	{
		throw new System.NotImplementedException();
	}

}

