//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CrossingA : Crossing
{

    public CrossingA(int crossingID) : base(crossingID) { }

	public virtual object SensorTime
	{
		get;
		set;
	}

	public virtual object State
	{
		get;
		set;
	}

	public virtual object Timer
	{
		get;
		set;
	}

	public virtual void TimerHandeler()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetState()
	{
		throw new System.NotImplementedException();
	}

}

