//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Drawing;

public class Feeder
{
	public virtual int FeederID
	{
		get;
		set;
	}

	public virtual int RightPercentage
	{
		get;
		set;
	}

	public virtual int LeftPercentage
	{
		get;
		set;
	}

	public virtual int StraightPercentage
	{
		get;
		set;
	}

	public virtual int CarsLimit
	{
		get;
		set;
	}

	public virtual int CarsOnBoard
	{
		get;
		set;
	}

	public virtual TrafficLight TrafficLight
	{
		get;
		set;
	}

	public virtual List<Point> StopPoins
	{
		get;
		set;
	}

	public virtual void AddDetailes()
	{
		throw new System.NotImplementedException();
	}

}

