//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Drawing;

public class Grid
{
    private List<GridCell> gridCells;

    public Grid()
    {
        gridCells = new List<GridCell>();
        CreateGridCells();
    }

    public void CreateGridCells()
    {
        for (int i = 0; i < 3; i+=200)
        {
            for (int i2 = 0; i2 < 4; i2+=200)
            {
                gridCells.Add(new GridCell(new Point(i, i2)));
            }
        }
    }

	public int GridRows
	{
		get;
		set;
	}

	public int GridColumns
	{
		get;
		set;
	}

	public virtual List <GridCell> GridCells
	{
		get;
		set;
	}

    //public IEnumerable<GridCell> GridCell
    //{
    //    get;
    //    set;
    //}

	public void DrawGrid()
	{
		throw new System.NotImplementedException();
	}

	public void CheckGridFull()
	{
		throw new System.NotImplementedException();
	}

	public void DeleteCrossing(object CellNumber)
	{
		throw new System.NotImplementedException();
	}

}

