//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Drawing;

public class GridCell
{
    private Point location;
    private Crossing Crossing;

    public GridCell(Point location)
    {
        this.location = location;
    }
    public void AddCrossing(Crossing c)
    {
        Crossing = c;
    }

    public Point ReturnLocation()
    {
        return location;
    }
    public Point TopLeft
    {
        get;
        set;
    }

    public int CellNumber
    {
        get;
        set;
    }

    public int CrossingID
    {
        get;
        set;
    }

    public int Size
    {
        get;
        set;
    }

    public void IsInCell()
    {

    }

    public void DrawCrossing()
    {

    }

}

