//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Neighbours
{
	public virtual Crossing Left
	{
		get;
		set;
	}

	public virtual Crossing Right
	{
		get;
		set;
	}

	public virtual Crossing Top
	{
		get;
		set;
	}

	public virtual Crossing Bottom
	{
		get;
		set;
	}

	public virtual void MoveBetweenCrossing()
	{
		throw new System.NotImplementedException();
	}

}

