//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Neighbours
{
	public Crossing Left
	{
		get;
		set;
	}

	public Crossing Right
	{
		get;
		set;
	}

	public Crossing Top
	{
		get;
		set;
	}

	public Crossing Bottom
	{
		get;
		set;
	}

	public void MoveBetweenCrossing()
	{
		
	}

}

