//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Grid
{
	public virtual int GridRows
	{
		get;
		set;
	}

	public virtual int GridColumns
	{
		get;
		set;
	}

	public virtual List <GridCell> GridCells
	{
		get;
		set;
	}

	public virtual Form Form
	{
		get;
		set;
	}

	public virtual IEnumerable<GridCell> GridCell
	{
		get;
		set;
	}

	public virtual void DrawGrid()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CheckGridFull()
	{
		throw new System.NotImplementedException();
	}

	public virtual void DeleteCrossing(object CellNumber)
	{
		throw new System.NotImplementedException();
	}

}

