//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GridCell
{
	public virtual Point TopLeft
	{
		get;
		set;
	}

	public virtual int CellNumber
	{
		get;
		set;
	}

	public virtual int CrossingID
	{
		get;
		set;
	}

	public virtual Form Form
	{
		get;
		set;
	}

	public virtual int Size
	{
		get;
		set;
	}

	public virtual Crossing Crossing
	{
		get;
		set;
	}

	public virtual void IsInCell()
	{
		throw new System.NotImplementedException();
	}

	public virtual void DrawCrossing()
	{
		throw new System.NotImplementedException();
	}

}

