//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


public class Simulator
{
	public string StreetName
	{
		get;
		set;
	}

	public  List <Crossing>
	{
		get;
		set;
	}

	public  DateTime Time
	{
		get;
		set;
	}

	public virtual List <Cars> CarsList
	{
		get;
		set;
	}

	public virtual Grid Grid
	{
		get;
		set;
	}

	public virtual Form Form
	{
		get;
		set;
	}

	public virtual IEnumerable<Cars> Cars
	{
		get;
		set;
	}

	public virtual void Run()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Save()
	{
		throw new System.NotImplementedException();
	}

}

